services:
  app:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.50"
        reservations:
          memory: 256M
          cpus: "0.25"
    image: ${DOCKER_USERNAME}/${APP_NAME}:${IMAGE_TAG:-latest}
    container_name: inktrack-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8081}:8080"
    environment:
      # Database Configuration
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}


      # Security Configuration
      API_SECRET_KEY: ${API_SECRET_KEY}

      # Frontend URL
      FRONT_URL: ${FRONT_URL}

      # Server Configuration
      SERVER_CONTEXT_PATH: ${SERVER_CONTEXT_PATH:-/api/v1}

      # Spring Profile
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}

    depends_on:
      db:
        condition: service_healthy

    networks:
      - inktrack-network

    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080${SERVER_CONTEXT_PATH:-/api/v1}/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:16.8-alpine
    container_name: inktrack-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_inktrack:/var/lib/postgresql/data
    networks:
      - inktrack-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  inktrack-network:
    driver: bridge

volumes:
  postgres_data_inktrack:
    driver: local
